{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "f988d2e0",
   "metadata": {},
   "source": [
    "Q1. What are the two latest user-defined exception constraints in Python 3.X?\n",
    "Ans : 1) Users can define custom exceptions by creating a new class. This exception class has to be derived, either directly or indirectly, from the built-in Exception class. Most of the built-in exceptions are also derived from this class.\n",
    "      2) User can created a user-defined exception called CustomError which inherits from the Exception class. This new exception, like other exceptions, can be raised using the raise statement with an optional error message.\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "Q2. How are class-based exceptions that have been raised matched to handlers?\n",
    "Ans: Class-based exceptions are realized as instances of exception classes. Exception classes are either predefined globally in the system or can be defined by the user (globally or locally). Class-based exceptions are raised either by the ABAP runtime environment or by a program.\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "Q3. Describe two methods for attaching context information to exception artifacts.\n",
    "Ans: To chain exceptions, use the raise from statement instead of a simple raise statement. This will give you information about both errors.\n",
    "\n",
    "def example():\n",
    "    try:\n",
    "        int('N/A')\n",
    "    except ValueError as e:\n",
    "        raise RuntimeError('A parsing error occurred') from e...\n",
    "  \n",
    "example()\n",
    "\n",
    "\n",
    "\n",
    "Q4. Describe two methods for specifying the text of an exception object's error message.\n",
    "Ans: To catch and print an exception that occurred in a code snippet, wrap it in an indented try block, followed by the command \"except Exception as e\" that catches the exception and saves its error message in string variable e. You can now print the error message with \"print(e)\" or use it for further processing.\n",
    "\n",
    "try:\n",
    "    # ... YOUR CODE HERE ... #\n",
    "except Exception as e:\n",
    "    # ... PRINT THE ERROR MESSAGE ... #\n",
    "    print(e)\n",
    "    \n",
    "The ValueError arises if you try to use wrong values in some functions. Hereâ€™s an example where the ValueError is raised because you tried to calculate the square root of a negative number:\n",
    "\n",
    "example 1:\n",
    "import math\n",
    "try:\n",
    "    a = math.sqrt(-2)\n",
    "except Exception as e:\n",
    "    print(e)\n",
    "print('Am I executed?')\n",
    "\n",
    "example 2: \n",
    "import logging\n",
    "\n",
    "logger = logging.getLogger()\n",
    "\n",
    "try:\n",
    "    x = 1/0\n",
    "except Exception as e:\n",
    "    logger.exception('Exception occurred while code execution: ' + str(e))\n",
    "\n",
    "\n",
    "\n",
    "Q5. Why do you no longer use string-based exceptions?\n",
    "Ans: In Python versions 1.5 and later, the standard exceptions are Python classes, and a few new standard exceptions have been added. The obsolete AccessError exception has been deleted. Because it is possible (although unlikely) that this change broke existing code, the Python interpreter can be invoked the command line option -X to disable this feature, and use string exceptions like before. This option is a temporary measure - eventually the string-based standard exceptions will be removed from the language altogether. It hasn't been decided whether user-defined string exceptions will be allowed in Python 2.0."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
